language: scala
scala:
   - 2.11.4

install:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xzvf protobuf-2.6.1.tar.gz
  - pushd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install && popd

script:
  - jdk_switcher use oraclejdk8
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - sbt "testOnly -- -l edu.colorado.plv.fixr.tests.TestParseSources"
  - jdk_switcher use openjdk7
  - sbt -java-home $JAVA_HOME test
