language: scala

matrix:
  - scala: 2.11.4
  - env: JDK=openjdk8

install:
  - wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip -d protoc protoc.zip
  - export PATH=$PWD/protoc/bin:$PATH
  - echo $PATH

script:
  - sbt "testOnly -- -l edu.colorado.plv.fixr.tests.TestParseSources"
